import { jsPDF } from "jspdf";
import QRCode from "qrcode";

/**
 * Generates a professional PDF certificate for a verified product
 * @param {Object} productData - Data retrieved from blockchain
 */
export const generateCertificate = async (productData) => {
    const {
        productId,
        productName,
        warrantyStart,
        warrantyEnd,
        isValid,
        daysRemaining,
        ownerName,
        ownerAddress,
        ownerContact,
        contractAddress,
        network = "Hardhat Localhost"
    } = productData;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPos = 20;

    // Helper for sections
    const addSectionTitle = (title) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(50, 50, 50);
        yPos += 15;
        doc.text(title, margin, yPos);
        yPos += 5;
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 10;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(80, 80, 80);
    };

    const addField = (label, value) => {
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, margin, yPos);
        doc.setFont("helvetica", "normal");
        doc.text(String(value), margin + 50, yPos);
        yPos += 8;
    };

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(0, 51, 102);
    const title = "WARRANTYCHAIN VERIFICATION CERTIFICATE";
    const titleWidth = doc.getTextWidth(title);
    doc.text(title, (pageWidth - titleWidth) / 2, yPos);

    yPos += 10;
    doc.setLineWidth(1);
    doc.setDrawColor(0, 51, 102);
    doc.line(margin, yPos, pageWidth - margin, yPos);

    // Product Section
    addSectionTitle("PRODUCT DETAILS");
    addField("Product Name", productName || "N/A");
    addField("Product ID", productId || "N/A");
    addField("Warranty Start", warrantyStart ? new Date(warrantyStart * 1000).toLocaleDateString() : "N/A");
    addField("Warranty End", warrantyEnd ? new Date(warrantyEnd * 1000).toLocaleDateString() : "N/A");

    // Owner Section
    addSectionTitle("OWNER INFORMATION");
    addField("Owner Name", ownerName || "N/A");
    addField("Owner Address", ownerAddress || "N/A");
    addField("Owner Contact", ownerContact || "N/A");

    // Warranty Section
    addSectionTitle("WARRANTY STATUS");
    const status = isValid ? "VALID" : "EXPIRED";
    doc.setFont("helvetica", "bold");
    if (isValid) {
        doc.setTextColor(0, 150, 0); // Green
    } else {
        doc.setTextColor(200, 0, 0); // Red
    }
    addField("Status", status);
    doc.setTextColor(80, 80, 80);
    addField("Days Remaining", daysRemaining !== undefined ? daysRemaining : "N/A");

    // Blockchain Section
    addSectionTitle("BLOCKCHAIN RECORD");
    addField("Contract Address", contractAddress || "N/A");
    addField("Network", network);
    addField("Verification Time", new Date().toLocaleString());

    // QR Code
    try {
        const verificationLink = `${window.location.origin}/verify/${productId}`;
        const qrBase64 = await QRCode.toDataURL(verificationLink);
        const qrSize = 40;
        doc.addImage(qrBase64, "PNG", pageWidth - margin - qrSize, yPos - 100, qrSize, qrSize);
    } catch (err) {
        console.error("Could not generate QR code for PDF", err);
    }

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    const footer = "This is a blockchain-verified document generated by WarrantyChain System.";
    doc.text(footer, (pageWidth - doc.getTextWidth(footer)) / 2, 285);

    // Save PDF
    doc.save(`WarrantyChain-Certificate-${productId || "Unknown"}.pdf`);
};
